# Generated by Django 2.0.5 on 2018-11-18 09:34

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startFundraiser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cc', 'campaign created'), ('cd', 'campaign started'), ('ces', 'campaign ended successfully'), ('ceu', 'campaign ended unsuccessfully')], default='cc', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Campaign Status',
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='update',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startFundraiser.Campaign'),
        ),
        migrations.AddField(
            model_name='comment',
            name='camp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='startFundraiser.Campaign'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='startFundraiser.comment'),
        ),
        migrations.AddField(
            model_name='campaignstatus',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='startFundraiser.Campaign'),
        ),
    ]
