# Generated by Django 2.0.5 on 2018-12-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0012_auto_20181202_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_Date',
            field=models.DateField(),
        ),
    ]
