# Generated by Django 2.0.6 on 2018-12-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0013_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='order',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
