# Generated by Django 2.0.6 on 2018-12-08 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0014_auto_20181206_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backers',
            name='backer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
