# Generated by Django 2.0.6 on 2018-12-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0015_auto_20181208_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backers',
            name='backer',
            field=models.CharField(max_length=50),
        ),
    ]
