# Generated by Django 2.0.6 on 2018-12-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0016_auto_20181208_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='backers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
