# Generated by Django 2.0.6 on 2018-12-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0017_backers_email'),
        ('startFundraiser', '0013_auto_20181202_2040'),
    ]

    operations = [
    ]
